#            __    __           _     _   ___ _            _
#    __  __/ / /\ \ \___  _ __| | __| | / __\ | ___   ___| | _____ _ __
#    \ \/ /\ \/  \/ / _ \| '__| |/ _` |/__\// |/ _ \ / __| |/ / _ \ '__|
#     >  <  \  /\  / (_) | |  | | (_| / \/  \ | (_) | (__|   <  __/ |
#    /_/\_\  \/  \/ \___/|_|  |_|\__,_\_____/_|\___/ \___|_|\_\___|_|
#                     xPlugins - WillfryDev - 777 Studios

# Lista de mundos que quieres bloquear.
# Para entrar a estos mundos, el jugador necesitará el permiso: xworldblocker.bypass.<nombredelmundo>
# Por ejemplo, para entrar a 'eventos', necesitará 'xworldblocker.bypass.eventos'.
# Si un jugador tiene 'xworldblocker.bypass.*', podrá entrar a todos los mundos.
blocked-worlds:
  - "eventos"
  - "staff_zone"
  - "mundo_vip"

# Mensajes del plugin. Puedes usar colores HEX (&#RRGGBB) y códigos de color de Minecraft (&a, &l, etc.).
# Si dejas un mensaje en blanco (''), no se enviará nada.
messages:
  reload: "&#A2E4B8 ✔ ¡Listo! &#C1FFD7La configuración de xWorldBlocker ha sido recargada."
  no-permission-entry: "&#FFB6C1 ✘ ¡Error! &#FFDDC1No tienes permisos para entrar a este mundo."
  no-permission-command: "&#FFB6C1 ✘ ¡Error! &#FFDDC1No tienes permisos para usar este comando."
  help:
    - ""
    - "&#A2E4B8/xwb reload &#87CEEB- Recarga la configuración del plugin."
    - "&#A2E4B8/xwb help &#87CEEB- Muestra este mensaje de ayuda."
    - ""

#         ____
#  __  _|  _ \
#  \ \/ / |_) |
#   >  <|  __/
#  /_/\_\_|lugins
#           Org.